.eslintrc.json
debug.js
gulpfile.babel.js
index.js
metadata-fetcher.js
metadata-handler.js
package.json
tests/index.js
tests/metadata-fetcher.js
tests/metadata-handler.js
tests/utils.js
utils.js
yarn.lock

This is identical to #126, but migrating it to my new fork.
Closes #127.

Use ESLint Shared Configuration

---

index.js
metadata.json
tests/index.js

Creating this in favor of #122

Obfuscate the real username to enforce uniqueness (2)

---

metadata-handler.js
tests/metadata-handler.js

Because @alias-mac prefers them this way 😛

metadata-handler: Indent case statements and use braces

---

package.json
yarn.lock

Nothing dangerous for us. https://github.com/babel/babel-eslint/releases

Upgrade babel-eslint to 7.2.1

---

package.json

I just like this way of spelling my name better.

Rename Robert to Bob W. in package.json

---

README.md

README.md: Fix grammar

---

debug.js
gulpfile.babel.js
index.js
metadata-fetcher.js
metadata-handler.js
package.json
tests/index.js
tests/metadata-handler.js
tests/utils.js
yarn.lock

This corresponds with the new 1.1.0 release of eslint-config-sugarcrm.

Update eslint config

---

package.json
yarn.lock

Upgrade commander to 2.11.0

---

.travis.yml

Run Node 8 on Travis CI and allow failures. For #170

---

package.json

This will ease the transition away from gulp should
we ever choose to get rid of it.
(This is the first step on the way to #130)

Add doc npm script to generate documentation

---

tests/index.js

I previously fixed these as in the PoC #155 and promised to split them out into a separate PR. I appear to have forgotten to do that until now.

tests/index.js: Fix grammar for "clean up"

---

Docs.md

Docs.md: Fix module name typo

---

.travis.yml
package.json
yarn.lock

Update nock to 9.0.14 to fix Node 8

---

package.json
yarn.lock

Update gulp-spawn-mocha to 3.3.1

---

package.json
yarn.lock

Wait until #178 is merged first to ensure consistency in the yarn.lock file.

Update mocha to 3.5.3

---

package.json
yarn.lock

Update commander to 2.13.0

---

tests/metadata-handler.js

tests/metadata-handler.js: Improve code coverage

---

package.json
yarn.lock

Update eslint-plugin-import to 2.8.0

---

package.json
yarn.lock

Nothing interesting from our side.

Update nock to 9.0.22

---

package.json
yarn.lock

Update sinon to 4.4.6
